name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        dim1: [0,1,2,3,4,5,6,7]
        dim2: [0,1,2,3,4,5,6,7]
        dim3: [0,1,2,3,4,5,6,7]

    steps:
      - uses: actions/checkout@v2

      - name: Show basic system info
        run: |
          uname -a
          lscpu
          free -h
          df -h
          ip a
          ls
          pwd
          ls /etc/*release

      - name: Run job
        run: |
          python run.py ${{ matrix.dim1 }} ${{ matrix.dim2 }} ${{ matrix.dim3 }}
