name: CI0

on: push

jobs:
  run:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        dim1: [0]
        dim2: [0]
        dim3: [0]
        dim4: [0,1,2,3]

    steps:
      - uses: actions/checkout@v2

      - name: Show basic system info
        run: |
          uname -a
          lscpu
          free -h
          df -h
          ip a
          ls
          pwd
          ls /etc/*release

      - name: Run job
        run: |
          echo ${{ secrets.TUSHARE_PRO_TOKEN}} > env
          pip install tushare
          python run.py ${{ matrix.dim1 }} ${{ matrix.dim2 }} ${{ matrix.dim3 }} ${{ matrix.dim4 }}
